name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  upstream:  # id of input
    description: 'upstream'
    required: true
    default: 'World'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.upstream }}
